// Generated by CoffeeScript 1.3.1
var debug, log;

debug = {
  active: true,
  basicColor: "color:#828282; background-color:#f0f0f0"
};

log = console.debug;

log = function() {
  var a, arg, newArguments, options, str, _i, _len;
  a = new Array();
  newArguments = new Array();
  for (_i = 0, _len = arguments.length; _i < _len; _i++) {
    arg = arguments[_i];
    a[_i] = arg;
  }
  newArguments = a;
  if (typeof a[1] === "object") {
    options = a[1];
    if (typeof options["color"] === "string") {
      newArguments[1] = options["color"];
    }
    if (typeof options["name"] === "string") {
      str = newArguments[0];
      newArguments[0] = "%c[" + options["name"] + "] " + str;
    } else {
      str = a[0];
      newArguments[0] = "%c" + str;
    }
    if (options["active"]) {
      return console.debug.apply(console, newArguments);
    }
  } else {
    str = a[0];
    newArguments[0] = "%c" + str;
    newArguments.push(debug.basicColor);
    return console.debug.apply(console, newArguments);
  }
};
